TYPE=VIEW
query=(select `l`.`ID` AS `ID`,`l`.`LIDNR` AS `LIDNR`,`l`.`NAAM` AS `NAAM`,`l`.`ACHTERNAAM` AS `ACHTERNAAM`,`l`.`AVATAR` AS `AVATAR`,`l`.`MOBIEL` AS `MOBIEL`,`l`.`NOODNUMMER` AS `NOODNUMMER`,`l`.`TELEFOON` AS `TELEFOON`,`l`.`EMAIL` AS `EMAIL`,`l`.`INSTRUCTEUR` AS `INSTRUCTEUR`,`l`.`STARTLEIDER` AS `STARTLEIDER`,`l`.`HEEFT_BETAALD` AS `HEEFT_BETAALD`,`l`.`LIERIST` AS `LIERIST`,`t`.`OMSCHRIJVING` AS `LIDTYPE`,`l`.`LIDTYPE_ID` AS `LIDTYPE_ID`,`l`.`GPL_VERLOOPT` AS `GPL_VERLOOPT`,`l`.`MEDICAL_VERLOOPT` AS `MEDICAL_VERLOOPT`,`l`.`VERWIJDERD` AS `VERWIJDERD`,`LIDAANWEZIGVANDAAG`(`l`.`ID`) AS `AANWEZIG`,`LIDAANWEZIGGEWEESTVANDAAG`(`l`.`ID`) AS `AANWEZIG_GEWEEST`,coalesce((select `gezc_org_sadb`.`oper_aanwezig`.`LAATSTE_AANPASSING` from `gezc_org_sadb`.`oper_aanwezig` where `gezc_org_sadb`.`oper_aanwezig`.`LID_ID` = `l`.`ID` order by `gezc_org_sadb`.`oper_aanwezig`.`LAATSTE_AANPASSING` desc limit 0,1),`l`.`LAATSTE_AANPASSING`) AS `LAATSTE_AANPASSING` from (`gezc_org_sadb`.`ref_leden` `l` left join `gezc_org_sadb`.`types` `t` on(`l`.`LIDTYPE_ID` = `t`.`ID`)) where `l`.`VERWIJDERD` = 0)
md5=c3cd832d380d8728545a17a85a918d09
updatable=0
algorithm=0
definer_user=gezc_org_sadb
definer_host=%
suid=1
with_check_option=0
timestamp=2019-12-07 10:53:13
create-version=2
source=(select `l`.`ID` AS `ID`,`l`.`LIDNR` AS `LIDNR`,`l`.`NAAM` AS `NAAM`,`l`.`ACHTERNAAM` AS `ACHTERNAAM`,`l`.`AVATAR` AS `AVATAR`,`l`.`MOBIEL` AS `MOBIEL`,`l`.`NOODNUMMER` AS `NOODNUMMER`,`l`.`TELEFOON` AS `TELEFOON`,`l`.`EMAIL` AS `EMAIL`,`l`.`INSTRUCTEUR` AS `INSTRUCTEUR`,`l`.`STARTLEIDER` AS `STARTLEIDER`,`l`.`HEEFT_BETAALD` AS `HEEFT_BETAALD`,`l`.`LIERIST` AS `LIERIST`,`t`.`OMSCHRIJVING` AS `LIDTYPE`,`l`.`LIDTYPE_ID` AS `LIDTYPE_ID`,`l`.`GPL_VERLOOPT` AS `GPL_VERLOOPT`,`l`.`MEDICAL_VERLOOPT` AS `MEDICAL_VERLOOPT`,`l`.`VERWIJDERD` AS `VERWIJDERD`,`LIDAANWEZIGVANDAAG`(`l`.`ID`) AS `AANWEZIG`,`LIDAANWEZIGGEWEESTVANDAAG`(`l`.`ID`) AS `AANWEZIG_GEWEEST`,coalesce((select `oper_aanwezig`.`LAATSTE_AANPASSING` from `oper_aanwezig` where (`oper_aanwezig`.`LID_ID` = `l`.`ID`) order by `oper_aanwezig`.`LAATSTE_AANPASSING` desc limit 0,1),`l`.`LAATSTE_AANPASSING`) AS `LAATSTE_AANPASSING` from (`ref_leden` `l` left join `types` `t` on((`l`.`LIDTYPE_ID` = `t`.`ID`))) where (`l`.`VERWIJDERD` = 0))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=(select `l`.`ID` AS `ID`,`l`.`LIDNR` AS `LIDNR`,`l`.`NAAM` AS `NAAM`,`l`.`ACHTERNAAM` AS `ACHTERNAAM`,`l`.`AVATAR` AS `AVATAR`,`l`.`MOBIEL` AS `MOBIEL`,`l`.`NOODNUMMER` AS `NOODNUMMER`,`l`.`TELEFOON` AS `TELEFOON`,`l`.`EMAIL` AS `EMAIL`,`l`.`INSTRUCTEUR` AS `INSTRUCTEUR`,`l`.`STARTLEIDER` AS `STARTLEIDER`,`l`.`HEEFT_BETAALD` AS `HEEFT_BETAALD`,`l`.`LIERIST` AS `LIERIST`,`t`.`OMSCHRIJVING` AS `LIDTYPE`,`l`.`LIDTYPE_ID` AS `LIDTYPE_ID`,`l`.`GPL_VERLOOPT` AS `GPL_VERLOOPT`,`l`.`MEDICAL_VERLOOPT` AS `MEDICAL_VERLOOPT`,`l`.`VERWIJDERD` AS `VERWIJDERD`,`LIDAANWEZIGVANDAAG`(`l`.`ID`) AS `AANWEZIG`,`LIDAANWEZIGGEWEESTVANDAAG`(`l`.`ID`) AS `AANWEZIG_GEWEEST`,coalesce((select `gezc_org_sadb`.`oper_aanwezig`.`LAATSTE_AANPASSING` from `gezc_org_sadb`.`oper_aanwezig` where `gezc_org_sadb`.`oper_aanwezig`.`LID_ID` = `l`.`ID` order by `gezc_org_sadb`.`oper_aanwezig`.`LAATSTE_AANPASSING` desc limit 0,1),`l`.`LAATSTE_AANPASSING`) AS `LAATSTE_AANPASSING` from (`gezc_org_sadb`.`ref_leden` `l` left join `gezc_org_sadb`.`types` `t` on(`l`.`LIDTYPE_ID` = `t`.`ID`)) where `l`.`VERWIJDERD` = 0)
mariadb-version=100410
