TYPE=VIEW
query=(select `a`.`ID` AS `ID`,`l`.`ID` AS `LID_ID`,`l`.`NAAM` AS `NAAM`,`l`.`AVATAR` AS `AVATAR`,`l`.`LIDTYPE_ID` AS `LIDTYPE_ID`,`a`.`VOORKEUR_VLIEGTUIG_TYPE` AS `VOORKEUR_VLIEGTUIG_TYPE`,`a`.`VOORKEUR_VLIEGTUIG_ID` AS `VOORKEUR_VLIEGTUIG_ID`,`VOORKEURTYPE`(`a`.`VOORKEUR_VLIEGTUIG_TYPE`) AS `VOORKEUR_TYPE`,`REGCALL`(`a`.`VOORKEUR_VLIEGTUIG_ID`) AS `VOORKEUR_REGCALL`,`LIDVLIEGT`(`l`.`ID`) AS `LAATSTE_STARTTIJD`,time_format(timediff(curtime(),`LIDVLIEGT`(`l`.`ID`)),\'%H:%i\') AS `ACTUELE_VLIEGTIJD`,time_format(`a`.`AANKOMST`,\'%H:%i\') AS `AANKOMST`,time_format(`a`.`VERTREK`,\'%H:%i\') AS `VERTREK`,time_format(`WACHTTIJD`(`l`.`ID`),\'%H:%i\') AS `WACHTTIJD`,`l`.`INSTRUCTEUR` AS `INSTRUCTEUR`,`l`.`LIERIST` AS `LIERIST`,`l`.`STARTLEIDER` AS `STARTLEIDER`,case `LIDAANWEZIGVANDAAG`(`l`.`ID`) when 0 then \'false\' else \'true\' end AS `AANWEZIG`,`VLIEGERSTARTLIJSTVANDAAG`(`l`.`ID`) AS `STARTLIJST_VANDAAG`,time_format(`VLIEGERVLIEGTIJDVANDAAG`(`l`.`ID`),\'%H:%i\') AS `VLIEGTIJD_VANDAAG`,(select `sv`.`CALLSIGN` from `gezc_org_sadb`.`startlijst_view` `sv` where `sv`.`VLIEGER_ID` = `l`.`ID` and `sv`.`DATUM` = cast(current_timestamp() as date) and `sv`.`STARTTIJD` is null order by `sv`.`DAGNUMMER` desc limit 0,1) AS `VOLGEND_CALLSIGN`,`a`.`OPMERKING` AS `OPMERKING`,`a`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING` from (`gezc_org_sadb`.`oper_aanwezig` `a` join `gezc_org_sadb`.`ledenlijst_view` `l` on(`a`.`LID_ID` = `l`.`ID`)) where `a`.`DATUM` = cast(current_timestamp() as date))
md5=4ffda2c3b6195c425705be76514dad37
updatable=1
algorithm=0
definer_user=gezc_org_sadb
definer_host=%
suid=1
with_check_option=0
timestamp=2019-12-07 10:53:13
create-version=2
source=(select `a`.`ID` AS `ID`,`l`.`ID` AS `LID_ID`,`l`.`NAAM` AS `NAAM`,`l`.`AVATAR` AS `AVATAR`,`l`.`LIDTYPE_ID` AS `LIDTYPE_ID`,`a`.`VOORKEUR_VLIEGTUIG_TYPE` AS `VOORKEUR_VLIEGTUIG_TYPE`,`a`.`VOORKEUR_VLIEGTUIG_ID` AS `VOORKEUR_VLIEGTUIG_ID`,`VOORKEURTYPE`(`a`.`VOORKEUR_VLIEGTUIG_TYPE`) AS `VOORKEUR_TYPE`,`REGCALL`(`a`.`VOORKEUR_VLIEGTUIG_ID`) AS `VOORKEUR_REGCALL`,`LIDVLIEGT`(`l`.`ID`) AS `LAATSTE_STARTTIJD`,time_format(timediff(curtime(),`LIDVLIEGT`(`l`.`ID`)),\'%H:%i\') AS `ACTUELE_VLIEGTIJD`,time_format(`a`.`AANKOMST`,\'%H:%i\') AS `AANKOMST`,time_format(`a`.`VERTREK`,\'%H:%i\') AS `VERTREK`,time_format(`WACHTTIJD`(`l`.`ID`),\'%H:%i\') AS `WACHTTIJD`,`l`.`INSTRUCTEUR` AS `INSTRUCTEUR`,`l`.`LIERIST` AS `LIERIST`,`l`.`STARTLEIDER` AS `STARTLEIDER`,(case `LIDAANWEZIGVANDAAG`(`l`.`ID`) when 0 then \'false\' else \'true\' end) AS `AANWEZIG`,`VLIEGERSTARTLIJSTVANDAAG`(`l`.`ID`) AS `STARTLIJST_VANDAAG`,time_format(`VLIEGERVLIEGTIJDVANDAAG`(`l`.`ID`),\'%H:%i\') AS `VLIEGTIJD_VANDAAG`,(select `sv`.`CALLSIGN` from `startlijst_view` `sv` where ((`sv`.`VLIEGER_ID` = `l`.`ID`) and (`sv`.`DATUM` = cast(now() as date)) and isnull(`sv`.`STARTTIJD`)) order by `sv`.`DAGNUMMER` desc limit 0,1) AS `VOLGEND_CALLSIGN`,`a`.`OPMERKING` AS `OPMERKING`,`a`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING` from (`oper_aanwezig` `a` join `ledenlijst_view` `l` on((`a`.`LID_ID` = `l`.`ID`))) where (`a`.`DATUM` = cast(now() as date)))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=(select `a`.`ID` AS `ID`,`l`.`ID` AS `LID_ID`,`l`.`NAAM` AS `NAAM`,`l`.`AVATAR` AS `AVATAR`,`l`.`LIDTYPE_ID` AS `LIDTYPE_ID`,`a`.`VOORKEUR_VLIEGTUIG_TYPE` AS `VOORKEUR_VLIEGTUIG_TYPE`,`a`.`VOORKEUR_VLIEGTUIG_ID` AS `VOORKEUR_VLIEGTUIG_ID`,`VOORKEURTYPE`(`a`.`VOORKEUR_VLIEGTUIG_TYPE`) AS `VOORKEUR_TYPE`,`REGCALL`(`a`.`VOORKEUR_VLIEGTUIG_ID`) AS `VOORKEUR_REGCALL`,`LIDVLIEGT`(`l`.`ID`) AS `LAATSTE_STARTTIJD`,time_format(timediff(curtime(),`LIDVLIEGT`(`l`.`ID`)),\'%H:%i\') AS `ACTUELE_VLIEGTIJD`,time_format(`a`.`AANKOMST`,\'%H:%i\') AS `AANKOMST`,time_format(`a`.`VERTREK`,\'%H:%i\') AS `VERTREK`,time_format(`WACHTTIJD`(`l`.`ID`),\'%H:%i\') AS `WACHTTIJD`,`l`.`INSTRUCTEUR` AS `INSTRUCTEUR`,`l`.`LIERIST` AS `LIERIST`,`l`.`STARTLEIDER` AS `STARTLEIDER`,case `LIDAANWEZIGVANDAAG`(`l`.`ID`) when 0 then \'false\' else \'true\' end AS `AANWEZIG`,`VLIEGERSTARTLIJSTVANDAAG`(`l`.`ID`) AS `STARTLIJST_VANDAAG`,time_format(`VLIEGERVLIEGTIJDVANDAAG`(`l`.`ID`),\'%H:%i\') AS `VLIEGTIJD_VANDAAG`,(select `sv`.`CALLSIGN` from `gezc_org_sadb`.`startlijst_view` `sv` where `sv`.`VLIEGER_ID` = `l`.`ID` and `sv`.`DATUM` = cast(current_timestamp() as date) and `sv`.`STARTTIJD` is null order by `sv`.`DAGNUMMER` desc limit 0,1) AS `VOLGEND_CALLSIGN`,`a`.`OPMERKING` AS `OPMERKING`,`a`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING` from (`gezc_org_sadb`.`oper_aanwezig` `a` join `gezc_org_sadb`.`ledenlijst_view` `l` on(`a`.`LID_ID` = `l`.`ID`)) where `a`.`DATUM` = cast(current_timestamp() as date))
mariadb-version=100410
