TYPE=VIEW
query=(select `sl`.`ID` AS `ID`,`sl`.`DAGNUMMER` AS `DAGNUMMER`,`v`.`REGISTRATIE` AS `REGISTRATIE`,`v`.`CALLSIGN` AS `CALLSIGN`,`REGCALL`(`v`.`ID`) AS `REG_CALL`,`v`.`FLARM_CODE` AS `FLARM_CODE`,`sl`.`VLIEGTUIG_ID` AS `VLIEGTUIG_ID`,`sl`.`SLEEPKIST_ID` AS `SLEEPKIST_ID`,`sl`.`SLEEP_HOOGTE` AS `SLEEP_HOOGTE`,`sl`.`DATUM` AS `DATUM`,`sl`.`SOORTVLUCHT_ID` AS `SOORTVLUCHT_ID`,`sl`.`STARTMETHODE_ID` AS `STARTMETHODE_ID`,time_format(`sl`.`STARTTIJD`,\'%H:%i\') AS `STARTTIJD`,time_format(`sl`.`LANDINGSTIJD`,\'%H:%i\') AS `LANDINGSTIJD`,case when `sl`.`DATUM` = cast(current_timestamp() as date) then time_format(timediff(ifnull(`sl`.`LANDINGSTIJD`,curtime()),`sl`.`STARTTIJD`),\'%H:%i\') else case when `sl`.`LANDINGSTIJD` is not null then time_format(timediff(`sl`.`LANDINGSTIJD`,`sl`.`STARTTIJD`),\'%H:%i\') else \'\' end end AS `DUUR`,`sl`.`OPMERKING` AS `OPMERKING`,`sl`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`sl`.`VLIEGER_ID` AS `VLIEGER_ID`,`vl`.`NAAM` AS `VLIEGERNAAM_LID`,`sl`.`VLIEGERNAAM` AS `VLIEGERNAAM`,`sl`.`INZITTENDE_ID` AS `INZITTENDE_ID`,`il`.`NAAM` AS `INZITTENDENAAM_LID`,`sl`.`INZITTENDENAAM` AS `INZITTENDENAAM`,`sl`.`OP_REKENING_ID` AS `OP_REKENING_ID`,`rl`.`NAAM` AS `OP_REKENING`,`sv`.`OMSCHRIJVING` AS `SOORTVLUCHT`,`sm`.`OMSCHRIJVING` AS `STARTMETHODE`,`b`.`OMSCHRIJVING` AS `BAAN` from (((((((`gezc_org_sadb`.`oper_startlijst` `sl` left join `gezc_org_sadb`.`ref_leden` `vl` on(`sl`.`VLIEGER_ID` = `vl`.`ID`)) left join `gezc_org_sadb`.`ref_leden` `il` on(`sl`.`INZITTENDE_ID` = `il`.`ID`)) left join `gezc_org_sadb`.`ref_leden` `rl` on(`sl`.`OP_REKENING_ID` = `rl`.`ID`)) left join `gezc_org_sadb`.`ref_vliegtuigen` `v` on(`sl`.`VLIEGTUIG_ID` = `v`.`ID`)) left join `gezc_org_sadb`.`types` `b` on(`sl`.`BAAN_ID` = `b`.`ID`)) left join `gezc_org_sadb`.`types` `sv` on(`sl`.`SOORTVLUCHT_ID` = `sv`.`ID`)) left join `gezc_org_sadb`.`types` `sm` on(`sl`.`STARTMETHODE_ID` = `sm`.`ID`)) where `sl`.`VERWIJDERD` = 0)
md5=a8099d77c54d747d74608f16139055d1
updatable=0
algorithm=0
definer_user=gezc_org_sadb
definer_host=%
suid=1
with_check_option=0
timestamp=2019-12-07 10:53:13
create-version=2
source=(select `sl`.`ID` AS `ID`,`sl`.`DAGNUMMER` AS `DAGNUMMER`,`v`.`REGISTRATIE` AS `REGISTRATIE`,`v`.`CALLSIGN` AS `CALLSIGN`,`REGCALL`(`v`.`ID`) AS `REG_CALL`,`v`.`FLARM_CODE` AS `FLARM_CODE`,`sl`.`VLIEGTUIG_ID` AS `VLIEGTUIG_ID`,`sl`.`SLEEPKIST_ID` AS `SLEEPKIST_ID`,`sl`.`SLEEP_HOOGTE` AS `SLEEP_HOOGTE`,`sl`.`DATUM` AS `DATUM`,`sl`.`SOORTVLUCHT_ID` AS `SOORTVLUCHT_ID`,`sl`.`STARTMETHODE_ID` AS `STARTMETHODE_ID`,time_format(`sl`.`STARTTIJD`,\'%H:%i\') AS `STARTTIJD`,time_format(`sl`.`LANDINGSTIJD`,\'%H:%i\') AS `LANDINGSTIJD`,(case when (`sl`.`DATUM` = cast(now() as date)) then time_format(timediff(ifnull(`sl`.`LANDINGSTIJD`,curtime()),`sl`.`STARTTIJD`),\'%H:%i\') else (case when (`sl`.`LANDINGSTIJD` is not null) then time_format(timediff(`sl`.`LANDINGSTIJD`,`sl`.`STARTTIJD`),\'%H:%i\') else \'\' end) end) AS `DUUR`,`sl`.`OPMERKING` AS `OPMERKING`,`sl`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`sl`.`VLIEGER_ID` AS `VLIEGER_ID`,`vl`.`NAAM` AS `VLIEGERNAAM_LID`,`sl`.`VLIEGERNAAM` AS `VLIEGERNAAM`,`sl`.`INZITTENDE_ID` AS `INZITTENDE_ID`,`il`.`NAAM` AS `INZITTENDENAAM_LID`,`sl`.`INZITTENDENAAM` AS `INZITTENDENAAM`,`sl`.`OP_REKENING_ID` AS `OP_REKENING_ID`,`rl`.`NAAM` AS `OP_REKENING`,`sv`.`OMSCHRIJVING` AS `SOORTVLUCHT`,`sm`.`OMSCHRIJVING` AS `STARTMETHODE`,`b`.`OMSCHRIJVING` AS `BAAN` from (((((((`oper_startlijst` `sl` left join `ref_leden` `vl` on((`sl`.`VLIEGER_ID` = `vl`.`ID`))) left join `ref_leden` `il` on((`sl`.`INZITTENDE_ID` = `il`.`ID`))) left join `ref_leden` `rl` on((`sl`.`OP_REKENING_ID` = `rl`.`ID`))) left join `ref_vliegtuigen` `v` on((`sl`.`VLIEGTUIG_ID` = `v`.`ID`))) left join `types` `b` on((`sl`.`BAAN_ID` = `b`.`ID`))) left join `types` `sv` on((`sl`.`SOORTVLUCHT_ID` = `sv`.`ID`))) left join `types` `sm` on((`sl`.`STARTMETHODE_ID` = `sm`.`ID`))) where (`sl`.`VERWIJDERD` = 0))
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=(select `sl`.`ID` AS `ID`,`sl`.`DAGNUMMER` AS `DAGNUMMER`,`v`.`REGISTRATIE` AS `REGISTRATIE`,`v`.`CALLSIGN` AS `CALLSIGN`,`REGCALL`(`v`.`ID`) AS `REG_CALL`,`v`.`FLARM_CODE` AS `FLARM_CODE`,`sl`.`VLIEGTUIG_ID` AS `VLIEGTUIG_ID`,`sl`.`SLEEPKIST_ID` AS `SLEEPKIST_ID`,`sl`.`SLEEP_HOOGTE` AS `SLEEP_HOOGTE`,`sl`.`DATUM` AS `DATUM`,`sl`.`SOORTVLUCHT_ID` AS `SOORTVLUCHT_ID`,`sl`.`STARTMETHODE_ID` AS `STARTMETHODE_ID`,time_format(`sl`.`STARTTIJD`,\'%H:%i\') AS `STARTTIJD`,time_format(`sl`.`LANDINGSTIJD`,\'%H:%i\') AS `LANDINGSTIJD`,case when `sl`.`DATUM` = cast(current_timestamp() as date) then time_format(timediff(ifnull(`sl`.`LANDINGSTIJD`,curtime()),`sl`.`STARTTIJD`),\'%H:%i\') else case when `sl`.`LANDINGSTIJD` is not null then time_format(timediff(`sl`.`LANDINGSTIJD`,`sl`.`STARTTIJD`),\'%H:%i\') else \'\' end end AS `DUUR`,`sl`.`OPMERKING` AS `OPMERKING`,`sl`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`sl`.`VLIEGER_ID` AS `VLIEGER_ID`,`vl`.`NAAM` AS `VLIEGERNAAM_LID`,`sl`.`VLIEGERNAAM` AS `VLIEGERNAAM`,`sl`.`INZITTENDE_ID` AS `INZITTENDE_ID`,`il`.`NAAM` AS `INZITTENDENAAM_LID`,`sl`.`INZITTENDENAAM` AS `INZITTENDENAAM`,`sl`.`OP_REKENING_ID` AS `OP_REKENING_ID`,`rl`.`NAAM` AS `OP_REKENING`,`sv`.`OMSCHRIJVING` AS `SOORTVLUCHT`,`sm`.`OMSCHRIJVING` AS `STARTMETHODE`,`b`.`OMSCHRIJVING` AS `BAAN` from (((((((`gezc_org_sadb`.`oper_startlijst` `sl` left join `gezc_org_sadb`.`ref_leden` `vl` on(`sl`.`VLIEGER_ID` = `vl`.`ID`)) left join `gezc_org_sadb`.`ref_leden` `il` on(`sl`.`INZITTENDE_ID` = `il`.`ID`)) left join `gezc_org_sadb`.`ref_leden` `rl` on(`sl`.`OP_REKENING_ID` = `rl`.`ID`)) left join `gezc_org_sadb`.`ref_vliegtuigen` `v` on(`sl`.`VLIEGTUIG_ID` = `v`.`ID`)) left join `gezc_org_sadb`.`types` `b` on(`sl`.`BAAN_ID` = `b`.`ID`)) left join `gezc_org_sadb`.`types` `sv` on(`sl`.`SOORTVLUCHT_ID` = `sv`.`ID`)) left join `gezc_org_sadb`.`types` `sm` on(`sl`.`STARTMETHODE_ID` = `sm`.`ID`)) where `sl`.`VERWIJDERD` = 0)
mariadb-version=100410
