TYPE=VIEW
query=select `al`.`ID` AS `ID`,`al`.`DATUM` AS `DATUM`,`al`.`POSITIE` AS `POSITIE`,`al`.`LID_ID` AS `LID_ID`,`al`.`VOORAANMELDING` AS `VOORAANMELDING`,`al`.`AANKOMST` AS `AANKOMST`,`al`.`VERTREK` AS `VERTREK`,`al`.`OVERLAND_VLIEGTUIG_ID` AS `OVERLAND_VLIEGTUIG_ID`,`al`.`VOORKEUR_VLIEGTUIG_TYPE` AS `VOORKEUR_VLIEGTUIG_TYPE`,`al`.`OPMERKINGEN` AS `OPMERKINGEN`,`al`.`VERWIJDERD` AS `VERWIJDERD`,`al`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,(select group_concat(`dev_sa`.`ref_types`.`CODE` separator \',\') from `dev_sa`.`ref_types` where `dev_sa`.`ref_types`.`GROEP` = 4 and `al`.`VOORKEUR_VLIEGTUIG_TYPE` like concat(\'%\',`dev_sa`.`ref_types`.`ID`,\'%\')) AS `VLIEGTUIGTYPE_CODE`,(select group_concat(`dev_sa`.`ref_types`.`OMSCHRIJVING` separator \',\') from `dev_sa`.`ref_types` where `dev_sa`.`ref_types`.`GROEP` = 4 and `al`.`VOORKEUR_VLIEGTUIG_TYPE` like concat(\'%\',`dev_sa`.`ref_types`.`ID`,\'%\')) AS `VLIEGTUIGTYPE_OMS`,`l`.`NAAM` AS `VLIEGER`,concat(ifnull(`v`.`REGISTRATIE`,\'\'),\' (\',ifnull(`v`.`CALLSIGN`,\'\'),\')\') AS `REGCALL` from ((`dev_sa`.`oper_aanwezig_leden` `al` left join `dev_sa`.`ref_leden` `l` on(`al`.`LID_ID` = `l`.`ID`)) left join `dev_sa`.`ref_vliegtuigen` `v` on(`al`.`OVERLAND_VLIEGTUIG_ID` = `v`.`ID`)) where `al`.`VERWIJDERD` = 0
md5=68fa617a77a58d7117d09b9bc036b760
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-01-23 21:03:29
create-version=2
source=SELECT \n					al.*,\n					(SELECT \n						GROUP_CONCAT(CODE) FROM ref_types \n					WHERE GROEP = 4 AND VOORKEUR_VLIEGTUIG_TYPE LIKE CONCAT(\'%\',ID,\'%\') ) AS VLIEGTUIGTYPE_CODE, \n					(SELECT \n						GROUP_CONCAT(OMSCHRIJVING) FROM ref_types \n					WHERE GROEP = 4 AND VOORKEUR_VLIEGTUIG_TYPE LIKE CONCAT(\'%\',ID,\'%\') ) AS VLIEGTUIGTYPE_OMS, 					\n					`l`.`NAAM` AS `VLIEGER`,  \n					CONCAT(IFNULL(`v`.`REGISTRATIE`,\'\'),\' (\',IFNULL(`v`.`CALLSIGN`,\'\'),\')\') AS `REGCALL`\n				FROM\n					`oper_aanwezig_leden` `al`\n				LEFT JOIN `ref_leden` `l` ON `al`.`LID_ID` = `l`.`ID`\n				LEFT JOIN `ref_vliegtuigen` `v` ON (`al`.`OVERLAND_VLIEGTUIG_ID` = `v`.`ID`)\n			WHERE\n					`al`.`VERWIJDERD` = 0
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `al`.`ID` AS `ID`,`al`.`DATUM` AS `DATUM`,`al`.`POSITIE` AS `POSITIE`,`al`.`LID_ID` AS `LID_ID`,`al`.`VOORAANMELDING` AS `VOORAANMELDING`,`al`.`AANKOMST` AS `AANKOMST`,`al`.`VERTREK` AS `VERTREK`,`al`.`OVERLAND_VLIEGTUIG_ID` AS `OVERLAND_VLIEGTUIG_ID`,`al`.`VOORKEUR_VLIEGTUIG_TYPE` AS `VOORKEUR_VLIEGTUIG_TYPE`,`al`.`OPMERKINGEN` AS `OPMERKINGEN`,`al`.`VERWIJDERD` AS `VERWIJDERD`,`al`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,(select group_concat(`dev_sa`.`ref_types`.`CODE` separator \',\') from `dev_sa`.`ref_types` where `dev_sa`.`ref_types`.`GROEP` = 4 and `al`.`VOORKEUR_VLIEGTUIG_TYPE` like concat(\'%\',`dev_sa`.`ref_types`.`ID`,\'%\')) AS `VLIEGTUIGTYPE_CODE`,(select group_concat(`dev_sa`.`ref_types`.`OMSCHRIJVING` separator \',\') from `dev_sa`.`ref_types` where `dev_sa`.`ref_types`.`GROEP` = 4 and `al`.`VOORKEUR_VLIEGTUIG_TYPE` like concat(\'%\',`dev_sa`.`ref_types`.`ID`,\'%\')) AS `VLIEGTUIGTYPE_OMS`,`l`.`NAAM` AS `VLIEGER`,concat(ifnull(`v`.`REGISTRATIE`,\'\'),\' (\',ifnull(`v`.`CALLSIGN`,\'\'),\')\') AS `REGCALL` from ((`dev_sa`.`oper_aanwezig_leden` `al` left join `dev_sa`.`ref_leden` `l` on(`al`.`LID_ID` = `l`.`ID`)) left join `dev_sa`.`ref_vliegtuigen` `v` on(`al`.`OVERLAND_VLIEGTUIG_ID` = `v`.`ID`)) where `al`.`VERWIJDERD` = 0
mariadb-version=100410
