TYPE=VIEW
query=select `di`.`ID` AS `ID`,`di`.`DATUM` AS `DATUM`,`di`.`VELD_ID` AS `VELD_ID`,`di`.`BAAN_ID` AS `BAAN_ID`,`di`.`BEDRIJF_ID` AS `BEDRIJF_ID`,`di`.`STARTMETHODE_ID` AS `STARTMETHODE_ID`,`di`.`OPMERKINGEN` AS `OPMERKINGEN`,`di`.`VLIEGBEDRIJF` AS `VLIEGBEDRIJF`,`di`.`METEO` AS `METEO`,`di`.`DIENSTEN` AS `DIENSTEN`,`di`.`VERSLAG` AS `VERSLAG`,`di`.`ROLLENDMATERIEEL` AS `ROLLENDMATERIEEL`,`di`.`VLIEGENDMATERIEEL` AS `VLIEGENDMATERIEEL`,`di`.`DDWV` AS `DDWV`,`di`.`CLUB_BEDRIJF` AS `CLUB_BEDRIJF`,`di`.`VERWIJDERD` AS `VERWIJDERD`,`di`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`T_Veld`.`CODE` AS `VELD_CODE`,`T_Veld`.`OMSCHRIJVING` AS `VELD_OMS`,`T_Baan`.`CODE` AS `BAAN_CODE`,`T_Baan`.`OMSCHRIJVING` AS `BAAN_OMS`,`T_Bedrijf`.`CODE` AS `BEDRIJF_CODE`,`T_Bedrijf`.`OMSCHRIJVING` AS `BEDRIJF_OMS`,`T_Startmethode`.`CODE` AS `STARTMETHODE_CODE`,`T_Startmethode`.`OMSCHRIJVING` AS `STARTMETHODE_OMS` from ((((`dev_sa`.`oper_daginfo` `di` left join `dev_sa`.`ref_types` `T_Veld` on(`di`.`VELD_ID` = `T_Veld`.`ID`)) left join `dev_sa`.`ref_types` `T_Baan` on(`di`.`BAAN_ID` = `T_Baan`.`ID`)) left join `dev_sa`.`ref_types` `T_Bedrijf` on(`di`.`BEDRIJF_ID` = `T_Bedrijf`.`ID`)) left join `dev_sa`.`ref_types` `T_Startmethode` on(`di`.`STARTMETHODE_ID` = `T_Startmethode`.`ID`)) where `di`.`VERWIJDERD` = 0
md5=7137b3a0cade27c6d282d04b2f234791
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-01-23 21:01:30
create-version=2
source=SELECT \n					di.*,\n					`T_Veld`.`CODE` AS `VELD_CODE`,\n					`T_Veld`.`OMSCHRIJVING` AS  `VELD_OMS`,        \n					`T_Baan`.`CODE` AS `BAAN_CODE`,\n					`T_Baan`.`OMSCHRIJVING` AS  `BAAN_OMS`,\n					`T_Bedrijf`.`CODE` AS `BEDRIJF_CODE`,\n					`T_Bedrijf`.`OMSCHRIJVING` AS  `BEDRIJF_OMS`,\n					`T_Startmethode`.`CODE` AS `STARTMETHODE_CODE`,\n					`T_Startmethode`.`OMSCHRIJVING` AS  `STARTMETHODE_OMS`\n				FROM\n					`oper_daginfo` `di`\n				LEFT JOIN `ref_types` `T_Veld` ON (`di`.`VELD_ID` = `T_Veld`.`ID`)\n				LEFT JOIN `ref_types` `T_Baan` ON (`di`.`BAAN_ID` = `T_Baan`.`ID`)\n				LEFT JOIN `ref_types` `T_Bedrijf` ON (`di`.`BEDRIJF_ID` = `T_Bedrijf`.`ID`)\n				LEFT JOIN `ref_types` `T_Startmethode` ON (`di`.`STARTMETHODE_ID` = `T_Startmethode`.`ID`)\n			WHERE\n					`di`.`VERWIJDERD` = 0
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `di`.`ID` AS `ID`,`di`.`DATUM` AS `DATUM`,`di`.`VELD_ID` AS `VELD_ID`,`di`.`BAAN_ID` AS `BAAN_ID`,`di`.`BEDRIJF_ID` AS `BEDRIJF_ID`,`di`.`STARTMETHODE_ID` AS `STARTMETHODE_ID`,`di`.`OPMERKINGEN` AS `OPMERKINGEN`,`di`.`VLIEGBEDRIJF` AS `VLIEGBEDRIJF`,`di`.`METEO` AS `METEO`,`di`.`DIENSTEN` AS `DIENSTEN`,`di`.`VERSLAG` AS `VERSLAG`,`di`.`ROLLENDMATERIEEL` AS `ROLLENDMATERIEEL`,`di`.`VLIEGENDMATERIEEL` AS `VLIEGENDMATERIEEL`,`di`.`DDWV` AS `DDWV`,`di`.`CLUB_BEDRIJF` AS `CLUB_BEDRIJF`,`di`.`VERWIJDERD` AS `VERWIJDERD`,`di`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`T_Veld`.`CODE` AS `VELD_CODE`,`T_Veld`.`OMSCHRIJVING` AS `VELD_OMS`,`T_Baan`.`CODE` AS `BAAN_CODE`,`T_Baan`.`OMSCHRIJVING` AS `BAAN_OMS`,`T_Bedrijf`.`CODE` AS `BEDRIJF_CODE`,`T_Bedrijf`.`OMSCHRIJVING` AS `BEDRIJF_OMS`,`T_Startmethode`.`CODE` AS `STARTMETHODE_CODE`,`T_Startmethode`.`OMSCHRIJVING` AS `STARTMETHODE_OMS` from ((((`dev_sa`.`oper_daginfo` `di` left join `dev_sa`.`ref_types` `T_Veld` on(`di`.`VELD_ID` = `T_Veld`.`ID`)) left join `dev_sa`.`ref_types` `T_Baan` on(`di`.`BAAN_ID` = `T_Baan`.`ID`)) left join `dev_sa`.`ref_types` `T_Bedrijf` on(`di`.`BEDRIJF_ID` = `T_Bedrijf`.`ID`)) left join `dev_sa`.`ref_types` `T_Startmethode` on(`di`.`STARTMETHODE_ID` = `T_Startmethode`.`ID`)) where `di`.`VERWIJDERD` = 0
mariadb-version=100410
