TYPE=VIEW
query=select `rooster`.`ID` AS `ID`,`rooster`.`DATUM` AS `DATUM`,`rooster`.`DDWV` AS `DDWV`,`rooster`.`CLUB_BEDRIJF` AS `CLUB_BEDRIJF`,`rooster`.`OCHTEND_DDI_ID` AS `OCHTEND_DDI_ID`,`rooster`.`OCHTEND_INSTRUCTEUR_ID` AS `OCHTEND_INSTRUCTEUR_ID`,`rooster`.`OCHTEND_LIERIST_ID` AS `OCHTEND_LIERIST_ID`,`rooster`.`OCHTEND_HULPLIERIST_ID` AS `OCHTEND_HULPLIERIST_ID`,`rooster`.`OCHTEND_STARTLEIDER_ID` AS `OCHTEND_STARTLEIDER_ID`,`rooster`.`MIDDAG_DDI_ID` AS `MIDDAG_DDI_ID`,`rooster`.`MIDDAG_INSTRUCTEUR_ID` AS `MIDDAG_INSTRUCTEUR_ID`,`rooster`.`MIDDAG_LIERIST_ID` AS `MIDDAG_LIERIST_ID`,`rooster`.`MIDDAG_HULPLIERIST_ID` AS `MIDDAG_HULPLIERIST_ID`,`rooster`.`MIDDAG_STARTLEIDER_ID` AS `MIDDAG_STARTLEIDER_ID`,`rooster`.`VERWIJDERD` AS `VERWIJDERD`,`rooster`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`dev_sa`.`ref_leden`.`NAAM` AS `OCHTEND_DDI`,`ref_leden_1`.`NAAM` AS `OCHTEND_INSTRUCTEUR`,`ref_leden_2`.`NAAM` AS `OCHTEND_HULPLIERIST`,`ref_leden_3`.`NAAM` AS `OCHTEND_STARTLEIDER`,`ref_leden_4`.`NAAM` AS `MIDDAG_DDI`,`ref_leden_5`.`NAAM` AS `MIDDAG_INSTRUCTEUR`,`ref_leden_6`.`NAAM` AS `MIDDAG_LIERIST`,`ref_leden_7`.`NAAM` AS `OCHTEND_LIERIST`,`ref_leden_8`.`NAAM` AS `MIDDAG_HULPLIERIST`,`ref_leden_9`.`NAAM` AS `MIDDAG_STARTLEIDER` from ((((((((((`dev_sa`.`oper_rooster` `rooster` left join `dev_sa`.`ref_leden` on(`rooster`.`OCHTEND_DDI_ID` = `dev_sa`.`ref_leden`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_1` on(`rooster`.`OCHTEND_INSTRUCTEUR_ID` = `ref_leden_1`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_2` on(`rooster`.`OCHTEND_HULPLIERIST_ID` = `ref_leden_2`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_3` on(`rooster`.`OCHTEND_STARTLEIDER_ID` = `ref_leden_3`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_4` on(`rooster`.`MIDDAG_DDI_ID` = `ref_leden_4`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_5` on(`rooster`.`MIDDAG_INSTRUCTEUR_ID` = `ref_leden_5`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_6` on(`rooster`.`MIDDAG_LIERIST_ID` = `ref_leden_6`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_7` on(`rooster`.`OCHTEND_LIERIST_ID` = `ref_leden_7`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_8` on(`rooster`.`MIDDAG_HULPLIERIST_ID` = `ref_leden_8`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_9` on(`rooster`.`MIDDAG_STARTLEIDER_ID` = `ref_leden_9`.`ID`)) where `rooster`.`VERWIJDERD` = 0
md5=8c9a7fe93e4664234b2b295ecd5f9e5b
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-01-23 21:02:56
create-version=2
source=SELECT \n					rooster.*,\n					ref_leden.NAAM AS OCHTEND_DDI,\n					ref_leden_1.NAAM AS OCHTEND_INSTRUCTEUR,\n					ref_leden_2.NAAM AS OCHTEND_HULPLIERIST,\n					ref_leden_3.NAAM AS OCHTEND_STARTLEIDER,\n					ref_leden_4.NAAM AS MIDDAG_DDI,\n					ref_leden_5.NAAM AS MIDDAG_INSTRUCTEUR,\n					ref_leden_6.NAAM AS MIDDAG_LIERIST,\n					ref_leden_7.NAAM AS OCHTEND_LIERIST,\n					ref_leden_8.NAAM AS MIDDAG_HULPLIERIST,\n					ref_leden_9.NAAM AS MIDDAG_STARTLEIDER\n				FROM\n					`oper_rooster` AS `rooster`\n					LEFT JOIN ref_leden         			ON (rooster.OCHTEND_DDI_ID = ref_leden.ID)\n					LEFT JOIN ref_leden AS ref_leden_1      ON (rooster.OCHTEND_INSTRUCTEUR_ID = ref_leden_1.ID)\n					LEFT JOIN ref_leden AS ref_leden_2      ON (rooster.OCHTEND_HULPLIERIST_ID = ref_leden_2.ID)\n					LEFT JOIN ref_leden AS ref_leden_3      ON (rooster.OCHTEND_STARTLEIDER_ID = ref_leden_3.ID)\n					LEFT JOIN ref_leden AS ref_leden_4      ON (rooster.MIDDAG_DDI_ID = ref_leden_4.ID)\n					LEFT JOIN ref_leden AS ref_leden_5      ON (rooster.MIDDAG_INSTRUCTEUR_ID = ref_leden_5.ID)\n					LEFT JOIN ref_leden AS ref_leden_6      ON (rooster.MIDDAG_LIERIST_ID = ref_leden_6.ID)\n					LEFT JOIN ref_leden AS ref_leden_7      ON (rooster.OCHTEND_LIERIST_ID = ref_leden_7.ID)\n					LEFT JOIN ref_leden AS ref_leden_8      ON (rooster.MIDDAG_HULPLIERIST_ID = ref_leden_8.ID)\n					LEFT JOIN ref_leden AS ref_leden_9      ON (rooster.MIDDAG_STARTLEIDER_ID = ref_leden_9.ID)				\n				WHERE\n					`rooster`.`VERWIJDERD` = 0
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `rooster`.`ID` AS `ID`,`rooster`.`DATUM` AS `DATUM`,`rooster`.`DDWV` AS `DDWV`,`rooster`.`CLUB_BEDRIJF` AS `CLUB_BEDRIJF`,`rooster`.`OCHTEND_DDI_ID` AS `OCHTEND_DDI_ID`,`rooster`.`OCHTEND_INSTRUCTEUR_ID` AS `OCHTEND_INSTRUCTEUR_ID`,`rooster`.`OCHTEND_LIERIST_ID` AS `OCHTEND_LIERIST_ID`,`rooster`.`OCHTEND_HULPLIERIST_ID` AS `OCHTEND_HULPLIERIST_ID`,`rooster`.`OCHTEND_STARTLEIDER_ID` AS `OCHTEND_STARTLEIDER_ID`,`rooster`.`MIDDAG_DDI_ID` AS `MIDDAG_DDI_ID`,`rooster`.`MIDDAG_INSTRUCTEUR_ID` AS `MIDDAG_INSTRUCTEUR_ID`,`rooster`.`MIDDAG_LIERIST_ID` AS `MIDDAG_LIERIST_ID`,`rooster`.`MIDDAG_HULPLIERIST_ID` AS `MIDDAG_HULPLIERIST_ID`,`rooster`.`MIDDAG_STARTLEIDER_ID` AS `MIDDAG_STARTLEIDER_ID`,`rooster`.`VERWIJDERD` AS `VERWIJDERD`,`rooster`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`dev_sa`.`ref_leden`.`NAAM` AS `OCHTEND_DDI`,`ref_leden_1`.`NAAM` AS `OCHTEND_INSTRUCTEUR`,`ref_leden_2`.`NAAM` AS `OCHTEND_HULPLIERIST`,`ref_leden_3`.`NAAM` AS `OCHTEND_STARTLEIDER`,`ref_leden_4`.`NAAM` AS `MIDDAG_DDI`,`ref_leden_5`.`NAAM` AS `MIDDAG_INSTRUCTEUR`,`ref_leden_6`.`NAAM` AS `MIDDAG_LIERIST`,`ref_leden_7`.`NAAM` AS `OCHTEND_LIERIST`,`ref_leden_8`.`NAAM` AS `MIDDAG_HULPLIERIST`,`ref_leden_9`.`NAAM` AS `MIDDAG_STARTLEIDER` from ((((((((((`dev_sa`.`oper_rooster` `rooster` left join `dev_sa`.`ref_leden` on(`rooster`.`OCHTEND_DDI_ID` = `dev_sa`.`ref_leden`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_1` on(`rooster`.`OCHTEND_INSTRUCTEUR_ID` = `ref_leden_1`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_2` on(`rooster`.`OCHTEND_HULPLIERIST_ID` = `ref_leden_2`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_3` on(`rooster`.`OCHTEND_STARTLEIDER_ID` = `ref_leden_3`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_4` on(`rooster`.`MIDDAG_DDI_ID` = `ref_leden_4`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_5` on(`rooster`.`MIDDAG_INSTRUCTEUR_ID` = `ref_leden_5`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_6` on(`rooster`.`MIDDAG_LIERIST_ID` = `ref_leden_6`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_7` on(`rooster`.`OCHTEND_LIERIST_ID` = `ref_leden_7`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_8` on(`rooster`.`MIDDAG_HULPLIERIST_ID` = `ref_leden_8`.`ID`)) left join `dev_sa`.`ref_leden` `ref_leden_9` on(`rooster`.`MIDDAG_STARTLEIDER_ID` = `ref_leden_9`.`ID`)) where `rooster`.`VERWIJDERD` = 0
mariadb-version=100410
