TYPE=VIEW
query=select `sl`.`ID` AS `ID`,`sl`.`DATUM` AS `DATUM`,`sl`.`DAGNUMMER` AS `DAGNUMMER`,`sl`.`VLIEGTUIG_ID` AS `VLIEGTUIG_ID`,`sl`.`STARTTIJD` AS `STARTTIJD`,`sl`.`LANDINGSTIJD` AS `LANDINGSTIJD`,`sl`.`STARTMETHODE_ID` AS `STARTMETHODE_ID`,`sl`.`VLIEGER_ID` AS `VLIEGER_ID`,`sl`.`INZITTENDE_ID` AS `INZITTENDE_ID`,`sl`.`VLIEGERNAAM` AS `VLIEGERNAAM`,`sl`.`INZITTENDENAAM` AS `INZITTENDENAAM`,`sl`.`SLEEPKIST_ID` AS `SLEEPKIST_ID`,`sl`.`SLEEP_HOOGTE` AS `SLEEP_HOOGTE`,`sl`.`VELD_ID` AS `VELD_ID`,`sl`.`OPMERKINGEN` AS `OPMERKINGEN`,`sl`.`VERWIJDERD` AS `VERWIJDERD`,`sl`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`v`.`REGISTRATIE` AS `REGISTRATIE`,`v`.`CALLSIGN` AS `CALLSIGN`,concat(ifnull(`v`.`REGISTRATIE`,\'\'),\' (\',ifnull(`v`.`CALLSIGN`,\'\'),\')\') AS `REGCALL`,case when `sl`.`DATUM` = cast(current_timestamp() as date) then time_format(timediff(ifnull(`sl`.`LANDINGSTIJD`,curtime()),`sl`.`STARTTIJD`),\'%H:%i\') else case when `sl`.`LANDINGSTIJD` is not null then time_format(timediff(`sl`.`LANDINGSTIJD`,`sl`.`STARTTIJD`),\'%H:%i\') else \'\' end end AS `DUUR`,`vl`.`NAAM` AS `VLIEGERNAAM_LID`,`il`.`NAAM` AS `INZITTENDENAAM_LID`,`sm`.`OMSCHRIJVING` AS `STARTMETHODE`,`veld`.`OMSCHRIJVING` AS `VELD` from (((((`dev_sa`.`oper_startlijst` `sl` left join `dev_sa`.`ref_leden` `vl` on(`sl`.`VLIEGER_ID` = `vl`.`ID`)) left join `dev_sa`.`ref_leden` `il` on(`sl`.`INZITTENDE_ID` = `il`.`ID`)) left join `dev_sa`.`ref_vliegtuigen` `v` on(`sl`.`VLIEGTUIG_ID` = `v`.`ID`)) left join `dev_sa`.`ref_types` `veld` on(`sl`.`VELD_ID` = `veld`.`ID`)) left join `dev_sa`.`ref_types` `sm` on(`sl`.`STARTMETHODE_ID` = `sm`.`ID`)) where `sl`.`VERWIJDERD` = 0
md5=894947da0b5935aab70f82cdb139e4bf
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=2
with_check_option=0
timestamp=2020-01-23 21:04:31
create-version=2
source=SELECT \n                    `sl`.*,\n                    `v`.`REGISTRATIE`   AS `REGISTRATIE`,\n                    `v`.`CALLSIGN`      AS `CALLSIGN`,\n                    CONCAT(IFNULL(`v`.`REGISTRATIE`,\'\'),\' (\',IFNULL(`v`.`CALLSIGN`,\'\'),\')\') AS `REGCALL`,\n                    CASE WHEN `sl`.`DATUM` = cast(current_timestamp() AS date) \n                        THEN \n                            time_format(timediff(ifnull(`sl`.`LANDINGSTIJD`,curtime()),`sl`.`STARTTIJD`),\'%H:%i\') \n                        ELSE \n                            CASE WHEN `sl`.`LANDINGSTIJD` IS NOT NULL\n                                THEN \n                                    time_format(timediff(`sl`.`LANDINGSTIJD`,`sl`.`STARTTIJD`),\'%H:%i\') \n                                ELSE \n                                    \'\' \n                                END \n                        END               AS `DUUR`,\n                    `vl`.`NAAM`           AS `VLIEGERNAAM_LID`,\n                    `il`.`NAAM`           AS `INZITTENDENAAM_LID`,\n                    `sm`.`OMSCHRIJVING`   AS `STARTMETHODE`,\n                    `veld`.`OMSCHRIJVING` AS `VELD` \n                FROM \n                    `oper_startlijst` `sl` \n                    LEFT JOIN `ref_leden`       `vl`    ON `sl`.`VLIEGER_ID` = `vl`.`ID` \n                    LEFT JOIN `ref_leden`       `il`    ON `sl`.`INZITTENDE_ID` = `il`.`ID` \n                    LEFT JOIN `ref_vliegtuigen` `v`     ON `sl`.`VLIEGTUIG_ID` = `v`.`ID` \n                    LEFT JOIN `ref_types`       `veld`  ON `sl`.`VELD_ID` = `veld`.`ID` \n                    LEFT JOIN `ref_types`       `sm`    ON `sl`.`STARTMETHODE_ID` = `sm`.`ID` \n				WHERE\n					`sl`.`VERWIJDERD` = 0
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `sl`.`ID` AS `ID`,`sl`.`DATUM` AS `DATUM`,`sl`.`DAGNUMMER` AS `DAGNUMMER`,`sl`.`VLIEGTUIG_ID` AS `VLIEGTUIG_ID`,`sl`.`STARTTIJD` AS `STARTTIJD`,`sl`.`LANDINGSTIJD` AS `LANDINGSTIJD`,`sl`.`STARTMETHODE_ID` AS `STARTMETHODE_ID`,`sl`.`VLIEGER_ID` AS `VLIEGER_ID`,`sl`.`INZITTENDE_ID` AS `INZITTENDE_ID`,`sl`.`VLIEGERNAAM` AS `VLIEGERNAAM`,`sl`.`INZITTENDENAAM` AS `INZITTENDENAAM`,`sl`.`SLEEPKIST_ID` AS `SLEEPKIST_ID`,`sl`.`SLEEP_HOOGTE` AS `SLEEP_HOOGTE`,`sl`.`VELD_ID` AS `VELD_ID`,`sl`.`OPMERKINGEN` AS `OPMERKINGEN`,`sl`.`VERWIJDERD` AS `VERWIJDERD`,`sl`.`LAATSTE_AANPASSING` AS `LAATSTE_AANPASSING`,`v`.`REGISTRATIE` AS `REGISTRATIE`,`v`.`CALLSIGN` AS `CALLSIGN`,concat(ifnull(`v`.`REGISTRATIE`,\'\'),\' (\',ifnull(`v`.`CALLSIGN`,\'\'),\')\') AS `REGCALL`,case when `sl`.`DATUM` = cast(current_timestamp() as date) then time_format(timediff(ifnull(`sl`.`LANDINGSTIJD`,curtime()),`sl`.`STARTTIJD`),\'%H:%i\') else case when `sl`.`LANDINGSTIJD` is not null then time_format(timediff(`sl`.`LANDINGSTIJD`,`sl`.`STARTTIJD`),\'%H:%i\') else \'\' end end AS `DUUR`,`vl`.`NAAM` AS `VLIEGERNAAM_LID`,`il`.`NAAM` AS `INZITTENDENAAM_LID`,`sm`.`OMSCHRIJVING` AS `STARTMETHODE`,`veld`.`OMSCHRIJVING` AS `VELD` from (((((`dev_sa`.`oper_startlijst` `sl` left join `dev_sa`.`ref_leden` `vl` on(`sl`.`VLIEGER_ID` = `vl`.`ID`)) left join `dev_sa`.`ref_leden` `il` on(`sl`.`INZITTENDE_ID` = `il`.`ID`)) left join `dev_sa`.`ref_vliegtuigen` `v` on(`sl`.`VLIEGTUIG_ID` = `v`.`ID`)) left join `dev_sa`.`ref_types` `veld` on(`sl`.`VELD_ID` = `veld`.`ID`)) left join `dev_sa`.`ref_types` `sm` on(`sl`.`STARTMETHODE_ID` = `sm`.`ID`)) where `sl`.`VERWIJDERD` = 0
mariadb-version=100410
