openapi: 3.0.2
info:
  title: Aanwezige Leden
  description: Welke leden zijn op een vliegdag aanwezig op het veld. Dan kunnen we sneller een keuze maken
  version: '1.0'
         
paths:
  /AanwezigLeden/CreateTable:
    post:
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat" 

  /AanwezigLeden/CreateViews:
    post:
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"    

  /AanwezigLeden/GetObject:
    get:
      summary: Haal een enkel record op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: false
          schema:
            type: integer
            format: int32
            example: 5
        - in: query
          name: LID_ID
          description: Lid ID (ID uit ref_leden). Werkt alleen als ID null is. Bovendien is DATUM vereist
          required: false
          schema:
            type: integer
            format: int32
            example: 10855
        - in: query
          name: DATUM
          description: DATUM van de vliegdag. Werkt alleen als ID null is. Bovendien is LID_ID vereist
          required: false
          schema:
            type: string
            format: date
            example: "1999-01-01"                     
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_leden'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"           
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"       

  /AanwezigLeden/GetObjects:
    get:
      summary: Haal de aanwezigheidslijst op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = NAAM
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string                                    
        - in: query        
          name: SELECTIE
          description: Zoek in de NAAM van de aanwezige
          required: false
          schema:
            type: string    
        - in: query        
          name: IN
          description: Een of meerdere leden database IDs in CSV formaat
          required: false
          schema:
            type: string                
        - in: query
          name: BEGIN_DATUM
          description: Begin datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date   
        - in: query
          name: EIND_DATUM
          description: Eind datum (inclusief deze dag)
          required: false
          schema:
            type: string
            format: date                                               
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/view_aanwezig_leden'
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"    

  /AanwezigLeden/Aanmelden:
    post:
      summary: Aanmelden van het lid als aanwezig. Maakt record aan als het niet bestaat of update bestaand record (ook al is het lid aanwezig)
      parameters:
        - in: query        
          name: LID_ID
          description: Het lid ID. Verwijzing naar leden tabel
          required: true
          schema:
            type: int
            example: 10408
        - in: query        
          name: TIJDSTIP
          description: Tijdstip van de aanmelding. Indien afwezig, huidige tijd. ISO8601
          required: false
          schema:
            type: string
            format: date-time 
            example: 2017-07-21T09:32:28Z         
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_leden' 
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /AanwezigLeden/Afmelden:
    post:
      summary: Afmelden van het lid als aanwezig. Update bestaand record. Lid moet aanwezig zijn
      parameters:
        - in: query        
          name: LID_ID
          description: Het lid ID. Verwijzing naar leden tabel
          required: true
          schema:
            type: int
            example: 10408
        - in: query        
          name: TIJDSTIP
          description: Tijdstip van de aanmelding. Indien afwezig, huidige tijd. ISO8601
          required: false
          schema:
            type: string
            format: date-time 
            example: 2017-07-21T09:32:28Z         
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_leden' 
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Lid is niet aanwezig"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 


  # /AanwezigLeden/PotentieelVliegtuig:
  #   get:
  #     summary: Geef een lijst terug waarop dit lid waarschijnlijk gaat vliegen op basis van de aanmelding of history. 
  #     parameters:
  #       - in: query
  #         name: LID_ID
  #         description: Lid ID (ID uit ref_leden). 
  #         required: true
  #         schema:
  #           type: integer
  #           format: int32
  #           example: 10855
  #       - in: query
  #         name: DATUM
  #         description: DATUM van de vliegdag. Indien niet aanwezig wordt de datum vandaag gebruikt
  #         required: false
  #         schema:
  #           type: string
  #           format: date
  #           example: "1999-01-01"         
  #       - in: query
  #         name: ALLEEN_AANWEZIG
  #         description: Beperk de lijst met vliegtuigen to die vliegtuigen die aanwezig zijn. Waarde 0..1
  #         required: false
  #         schema:
  #           type: boolean
  #           example: 0                     
  #     responses:
  #       200:
  #         description: "OK, data succesvol opgehaald"
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/oper_aanwezig_leden'
  #       404:
  #         description: "Data niet gevonden"
  #       405:
  #         description: "Methode niet toegestaan, input validatie error"  
  #       406:
  #         description: "Niet aanvaardbaar, input ontbreekt"           
  #       500:
  #         description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"

  /AanwezigLeden/DeleteObject:
    delete:
      summary: Markeer record als verwijderd.
      parameters:
        - in: query
          name: ID
          description: Database ID van het aanwezig record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        204:
          description: "Aanwezig record verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"        
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /AanwezigLeden/SaveObject:
    post:
      summary: Voeg nieuwe aanmelding toe
      requestBody:
        description: Aanmelding data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_aanwezig_leden'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_leden'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"                
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, lid is al aanwezig"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"                      
    put:
      summary: Update bestaande aanmelding. DATUM / LID_ID kunnen niet aangepast worden. Indien deze velden onjuist onjuist zijn, verwijder record en maak nieuw record.
      requestBody:
        description: Aanmelding data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_aanwezig_leden'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_aanwezig_leden'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"                
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"          
        409:
          description: "Conflict, lid is al/niet aanwezig op deze dag" 
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"  

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is

  schemas:
    oper_aanwezig_leden:
      type: object
      properties:
        ID:
          description: Database ID van het aanwezig record
          type: integer
          format: int32
          example: 12871
        DATUM:
          description: Datum van de vliegdag 
          type: string
          format: date
          example: 2017-07-21     
        POSITIE:
          description: De positie op de startlijst. Nummer 1 is staat hoger op de startlijst als nummer 2 
          type: int32
          minimum: 1
          example: 12
        LID_ID: 
          description: Het lid ID. Verwijzing naar leden tabel
          type: int
          example: 10408
        VOORAANMELDING: 
          description: Heeft het lid zich vooraf aangemeld (bijv ingeschreven via DDWV)?  Waarde 0..1
          type: boolean
          example: 0           
        AANKOMST: 
          description: Aankomsttijd van het lid. ISO8601
          type: string
          format: date-time 
          example: 2017-07-21T09:32:28Z       
        VERTREK: 
          description: Vertrektijd van het lid. ISO8601
          type: string
          format: date-time 
          example: 2017-07-21T17:32:28Z      
        OVERLAND_VLIEGTUIG_ID: 
          description: Lid wil graag overland met dit vliegtuig. Verwijzing naar vliegtuig tabel
          type: integer
          format: int32
          example: 200 
        VOORKEUR_VLIEGTUIG_TYPE:
          description: Op welke type wil dit lid vandaag vliegen? Types als CSV formaat
          type: integer
          format: int32
          example: 404, 405     
        OPMERKINGEN:
          description: Opmerking over de vliegdag 
          type: string
          example: Heeft in de ochtend lierdienst 
        VERWIJDERD:
          description: Is dit record gemarkeerd als verwijderd?  Waarde 0..1
          type: boolean
          example: 0            
        LAATSTE_AANPASSING:
          description: Tijdstempel van laaste aanpassing in de database
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
    view_aanwezig_leden:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
        dataset:
          description: De dataset met records
          type: array
          items: 
            type: object
            allOf:
              - $ref: '#/components/schemas/oper_aanwezig_leden'
              - type: object
                properties:
                  VLIEGER:
                    description: De volledige naam van het lid
                    type: string
                    example: Meindert het Paard                  
                  VLIEGTUIGTYPE_CODE: 
                    description: Korte beschrijving van het vliegtuig types
                    type: string
                    example: DCS, Duo
                  VLIEGTUIGTYPE_OMS: 
                    description: Beschrijving van het vliegtuig types
                    type: string
                    example: Discus CS, Duo Discus                    
                  REGCALL: 
                    description: Vliegtuig registratie en callsign van overland vliegtuig
                    type: string
                    example: PH-1076 (E2)  