openapi: 3.0.2
info:
  title: Daginfo
  description: Informatie over de vliegdag
  version: '1.0'
         
paths:
  /Daginfo/CreateTable:
    post:
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat" 

  /Daginfo/CreateViews:
    post:
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"       

  /Daginfo/GetObject:
    get:
      summary: Haal een enkel daginfo record op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het daginfo record
          required: false
          schema:
            type: integer
            format: int32
        - in: query
          name: DATUM
          description: Datum van de daginfo
          required: false
          schema:
            type: string
            format: date
            
            example: 2017-07-21   
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_daginfo'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"   
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"       

  /Daginfo/GetObjects:
    get:
      summary: Haal een lijst met vliegdagen op uit de database
      parameters:
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = DATUM DESC
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1 
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string                                               
        - in: query        
          name: DATUM
          description: Zoek op datum
          required: false
          schema:
            type: string
            format: date                          
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/view_daginfo'    
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"       

  /Daginfo/DeleteObject:
    delete:
      summary: Verwijder daginfo record
      parameters:
        - in: query
          name: ID
          description: Database ID van het daginfo record
          required: false
          schema:
            type: integer
            format: int32
        - in: query
          name: DATUM
          description: Datum van de daginfo
          required: false
          schema:
            type: string
            format: date
            example: 2017-07-21 
      responses:
        204:
          description: "Daginfo verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten" 
        404:
          description: "Data niet gevonden"             
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"             
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"      

  /Daginfo/SaveObject:
    post:
      summary: Voeg nieuw daginfo record toe
      requestBody:
        description: Daginfo data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_daginfo'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_daginfo'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"       
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        409:
          description: "Conflict, datum bestaat al"               
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"                         
    put:
      summary: Update bestaand daginfo record
      requestBody:
        description: Daginfo data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/oper_daginfo'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/oper_daginfo'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"  
        404:
          description: "Data niet gevonden"      
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        409:
          description: "Conflict, datum bestaat al"               
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"    
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is

  schemas:
    oper_daginfo:
      type: object
      properties:
        ID:
          description: Database ID van het daginfo record
          type: integer
          format: int32
          example: 12871
        DATUM:
          description: Datum van de vliegdag 
          type: string
          format: date
          example: 2017-07-21             
        BAAN_ID:
          description: Welke baan is in gebruik. Verwijzing naar type tabel. 
          type: integer
          format: int32
          example: 108    
        BEDRIJF_ID:
          description: Welke club is in verantwoordelijk voor het vliegbedrijf. Verwijzing naar type tabel. 
          type: integer
          format: int32
          example: 1550   
        DDWV:
          description: Is het een DDWV dag? Waarde 0..1
          type: boolean
          example: 0
        CLUB_BEDRIJF:
          description: Is er een clubbedrijf Waarde 0..1
          type: boolean
          example: 1          
        OPMERKINGEN:
          description: Opmerking over de vliegdag 
          type: string
          example: Zomerkamp dag 8                  
        VLIEGBEDRIJF:
          description: Beschrijving van de situatie op het veld
          type: string
          example: Het vliegbedrijf bevatte de volgende aspect(en), lier, sleep en zelfstart op de 22R met een rechterhand circuit. Halverwege de dag omgesteld naar 27C
        METEO:
          description: Beschrijving van de weerscondities
          type: string
          example: Het zicht was > 10 km. De windrichting was 270 met  windkracht 3.4 - 5.42 m/s. Er was 2/8 bewolking. De wolkenbasis was 800 meter hoog.          
        DIENSTEN: 
          description: Aanwezigheid van functionarissen 
          type: string
          example: Jan, Maartje, Mohammed aanwezig. Klaas had zich verslapen en kwam om 11:00      
        VERSLAG:
          description: Kort veslag van de dag
          type: string
          example: Rustige dag met een klein ploegje mensen ondanks het prachtige weer. Omstellen ging zonder problemen, vliegende kisten konden blijven hangen
        ROLLENDMATERIEEL:
          description: Opmerkingen over het rollend materieel
          type: string
          example: De motor van de lier wordt warm
        VLIEGENDMATERIEEL: 
          description: Opmerkingen over de vloot
          type: string
          example: De E11 is in de werkplaats gezet ivm lekke band. Wordt maandag opgelost     
        VERWIJDERD:
          description: Is dit record gemarkeerd als verwijderd?  Waarde 0..1
          type: boolean
          example: 0          
        LAATSTE_AANPASSING:
          description: Tijdstempel van laaste aanpassing in de database, laat leeg bij updates
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 
    view_daginfo:
      type: object
      properties:
        totaal:
          description: Aantal records dat voldoet aan de criteria in de database
          type: integer
          format: int32
          example: 287
        laatste_aanpassing:
          description: Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18  
        dataset:
          description: De dataset met records
          type: array
          items: 
            type: object
            allOf:
              - $ref: '#/components/schemas/oper_daginfo'
              - type: object
                properties:
                  VELD_CODE:
                    description: Verkorte naam van het vliegveld
                    type: string
                    example: EHTL
                  VELD_OMS: 
                    description: Naam van het vliegveld
                    type: string 
                    example: Terlet
                  BAAN_CODE: 
                    description: Verkorte beschrijving start strip
                    type: string
                    example: 22R
                  BAAN_OMS: 
                    description: beschrijving start strip
                    type: string 
                    example: RWY 22R
                  BEDRIJF_CODE:
                    description: Verkorte naam van de club die leiding heeft over vliegbedrijf
                    type: string
                    example: gezc
                  BEDRIJF_OMS:
                    description: Club die leiding heeft over vliegbedrijf
                    type: string 
                    example: GeZC
                  STARTMETHODE_CODE: 
                    description: De verkorte beschrijving van de meest gebruikte startmethode
                    type: string
                    example: Lier
                  STARTMETHODE_OMS: 
                    description: Beschrijving van de meest gebruikte startmethode
                    type: string
                    example: Lierstart           