openapi: 3.0.2
info:
  title: Type data
  description: Verzameling van types, bijvoorbeeld items in een combobox
  version: '1.0'
         
paths:
  /Types/CreateTable:
    post:
      summary: Creeer database objecten
      parameters:
        - in: query
          name: FILLDATA
          description: Dummy records aanmaken
          required: true
          schema:
            type: boolean
      responses:
        201:
          description: "Aangemaakt, Tabel toegevoegd"
        500:
          description: "Data verwerkingsfout, bijv omdat de tabel al bestaat"   

  /Types/CreateViews:
    post:
      summary: Creeer database views
      responses:
        201:
          description: "Aangemaakt, View toegevoegd"
        500:
          description: "Data verwerkingsfout, view niet aangemaak"    

  /Types/GetObject:
    get:
      summary: Haal een enkel record op uit de database
      parameters:
        - in: query
          name: ID
          description: Database ID van het type record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_types'
        404:
          description: "Data niet gevonden"
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"    
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"     

  /Types/GetObjects:
    get:
      summary: Haal een lijst met records op uit de database. Query parameters worden in AND conditie gebruikt
      parameters:
        - in: query
          name: LAATSTE_AANPASSING
          description: Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg
          required: false
          schema:
            type: boolean
        - in: query
          name: SORT
          description: Sortering van de velden in ORDER BY formaat. Default = CLUBKIST DESC, VOLGORDE, REGISTRATIE
          required: false
          schema:
            type: string     
        - in: query
          name: MAX
          description: Maximum aantal records in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query
          name: START
          description: Eerste record in de dataset. Gebruikt in LIMIT query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1  
        - in: query        
          name: VELDEN
          description: Welke velden moet opgenomen worden in de dataset
          required: false
          schema:
            type: string                                    
        - in: query
          name: GROEP
          description: Haal alle types op van een specieke groep
          required: false
          schema:
            type: string                           
      responses:
        200:
          description: "OK, data succesvol opgehaald"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_types'
        405:
          description: "Methode niet toegestaan, input validatie error"  
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"          

  /Types/DeleteObject:
    delete:
      summary: Markeer record als verwijderd.
      parameters:
        - in: query
          name: ID
          description: Database ID van het record
          required: true
          schema:
            type: integer
            format: int32
      responses:
        204:
          description: "Type verwijderd"
        401:
          description: "Niet geautoriseerd, geen schrijfrechten" 
        404:
          description: "Data niet gevonden"             
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"            
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)" 

  /Types/SaveObject:
    post:
      summary: Voeg nieuw type record toe
      requestBody:
        description: type data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ref_types'
      responses:
        200:
          description: "OK, data succesvol toegevoegd"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_types'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten"                          
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"   
        409:
          description: "Conflict, record bestaat al"                     
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"                       
    put:
      summary: Update bestaand type record
      requestBody:
        description: type data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ref_types'
      responses:
        200:
          description: "OK, data succesvol aangepast"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ref_types'  
        401:
          description: "Niet geautoriseerd, geen schrijfrechten" 
        404:
          description: "Data niet gevonden"                          
        405:
          description: "Methode niet toegestaan, input validatie error"  
        406:
          description: "Niet aanvaardbaar, input ontbreekt"             
        500:
          description: "Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer)"  

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Eerst inloggen voordat API beschikbaar is

  schemas:
    ref_types:
      type: object
      properties:
        ID:
          description: Database ID van het record
          type: integer
          format: int32
          example: 12871
        GROEP:
          description: Type groep
          type: integer
          format: int32
          example: 101
        CODE:
          description: Zeer korte beschrijving van de code
          type: string
          maxLength: 8
          example: "14R"
        EXT_REF:
          description: Hoe kennen andere systemen / organisatie deze code
          type: string
          maxLength: 25
        OMSCHRIJVING:
          description: Volledige omschrijving van het type
          type: string
          maxLength: 75
          example: Windkracht 3 (7-10 kn)
        SORTEER_VOLGORDE:
          description: Volgorde in de HMI
          type: integer
          format: int32
          example: 7
        READ_ONLY:
          description: Is dit record (met ID) hard gecodeerd in de source code. Zo ja, dan niet aanpassen. Waarde 0..1
          type: boolean
          example: 0
        VERWIJDERD:
          description: Is dit record gemarkeerd als verwijderd?  Waarde 0..1
          type: boolean
          example: 0        
        LAATSTE_AANPASSING:
          description: Tijdstempel van laaste aanpassing in de database
          type: string
          format: date-time   
          example: 2019-01-04 22:34:18 